config/routes.rb
Rails.application.routes.draw do
  get 'reviews/create'
  get 'reviews/destroy'
  devise_for :users
  root to: 'pages#home'

  resources :bikes do
    resources :reviews
  end
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/payment', to: 'pages#payment'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  has_one_attached :photo
  belongs_to :owner, class_name: "User"
  validates :name, :price_cents, :sku, :photo, :category, :address, presence: true
  has_many :reviews, dependent: :destroy
  has_many :orders, dependent: :destroy
  monetize :price_cents
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :bike
  monetize :amount_cents
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :bike
  validates :content, :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :owned_bikes, foreign_key: :owner_id, class_name: "Bike", dependent: :destroy
  has_many :orders, dependent: :destroy
  has_one_attached :avatar
  has_many :reviews, dependent: :destroy
  validates :email, :nickname, presence: true
  validates :nickname, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :avatar])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  skip_after_action :verify_policy_scoped, only: [:index, :show]
  before_action :set_bike, only: [:show, :edit, :update, :destroy]

  def index
    @bikes = Bike.geocoded # returns flats with coordinates

    @markers = @bikes.map do |bike|
      {
        lat: bike.latitude,
        lng: bike.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { bike: bike })
      }
    end

    @bikes = Bike.all
    authorize @bikes
  end

  def show
    @markers = [
      {
        lat: @bike.latitude,
        lng: @bike.longitude
      }
    ]
    @review = Review.new
  end

  def new
    @bike = Bike.new
    authorize @bike
  end

  def create
    @bike = Bike.new(bike_params)
    @bike.owner = current_user
    if @bike.save
      redirect_to bikes_path, notice: 'Bike was successfully created'
    else
      render :new, notice: 'something went wrong'
    end
    authorize @bike
  end

  def edit
  end

  def update
    if @bike.update(bike_params)
      redirect_to @bike, notice: 'bike was successfully update.'
    else
      render :edit
    end
  end

  def destroy
    @bike.destroy
    redirect_to bikes_path, notice: 'post was successfully destroyed.'
    authorize @bike
  end

  def my_own
  end

  private

  def set_bike
    @bike = Bike.find(params[:id])
    authorize @bike
  end

  def bike_params
    params.require(:bike).permit(:name, :sku, :category, :photo, :price_cents, :address)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_after_action :verify_policy_scoped, only: [:create, :show]

  def show
    @order = current_user.orders.find(params[:id])
    authorize @order
  end

  def create
    bike = Bike.find(params[:bike_id])
    order  = Order.create!(bike: bike, bike_sku: bike.sku, amount: bike.price, state: 'pending', user: current_user)

    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        name: bike.sku,
        images: [bike.photo],
        amount: bike.price_cents,
        currency: 'eur',
        quantity: 1
      }],
      success_url: payment_url,
      cancel_url: order_url(order)
    )

    order.update(checkout_session_id: session.id)
    redirect_to new_order_payment_path(order)
    authorize order
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def payment
    @bike = Bike.first
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  skip_after_action :verify_policy_scoped, only: [:new]

  def new
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
    authorize @order
  end

  #def payment
   # @bike = Restaurant.first.bikes.first
  #end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_bike
  before_action :find_review, only: [:destroy]

  def create
    if already_reviewed?
      flash[:notice] = "You can't review more than once"
    else
      @bike = Bike.find(params[:bike_id])
      @review = Review.new(review_params)
      @review.bike = @bike
      @review.user = current_user
      if @review.save
        redirect_to bike_path(@bike, anchor: "review-#{@review.id}")
      else
        flash[:alert] = "Something went wrong."
        render "bikes/show"
      end
    end
    authorize @bike
  end

  def destroy
    if !already_reviewed?
      flash[:notice] = "Cannot unreview"
    else
      @review.destroy
    end
    redirect_to bike_path(@bike)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def find_bike
    @bike = Bike.find(params[:bike_id])
  end

  def find_review
    @review = @bike.reviews.find(params[:id])
    authorize @review
  end

  def already_reviewed?
    Review.where(user_id: current_user.id, bike_id:
      params[:bike_id]).exists?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_form.html.erb
<%= simple_form_for (@bike), remote: true do |f|  %>
  <p><%= f.input :name, label: 'What is your bike\'s name?' %></p>
  <p><%= f.input :sku, label: 'What is the SKU?' %></p>
  <p><%= f.input :category, label: "What's the category of the bike?"  %></p>
  <p><%= f.input :price_cents, label: "What's the price of the bike?"  %></p>
  <p><%= f.input :address, label: "Where is the location of the bike?"  %></p>
  <p><%= f.input :photo, as: :file %></p>
  <p><%= f.submit class: "btn btn-primary"%></p>
<% end %>

app/views/bikes/_info_window.html.erb
<h2><%= bike.name %></h2>
<p><%= bike.address %></p>

app/views/bikes/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6 mt-2">
      <h4>Edit Your Bike here:</h4>
      <%= render 'form', bike: @bike  %>

      <%= link_to 'Show', @bike %>
    <%= link_to "back", bikes_path %>
    </div>

  </div>
</div>

app/views/bikes/index.html.erb
<div class="container">
<h1>Bikes</h1>
  <div class="row">
    <% @bikes.each do |bike| %>
      <div class="col-12  col-md-6 col-lg-3">
        <div class="card m-2">
          <%= cl_image_tag bike.photo.key , class: "card-img-top" %>
          <div class="card-body-infos">
            <div>
              <h4><%= bike.name  %></h4>
              <p><%= bike.category  %></p>
            </div>
            <% if bike.owner.avatar.attached? %>
              <%= cl_image_tag bike.owner.avatar.key, class: "card-body-user avatar-bordered" %>
            <% end %>
            <h4 class="card-body-pricing"><%= humanized_money_with_symbol(bike.price) %></h4>
        </div>
            <%= link_to "", bike_path(bike), class: 'card-link' %>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to 'back', root_path %>
</div>
<small>Reload page to get updated map display</small>
  <div id="map"
       style="width: 100%; height: 600px; border-radius: 16px; background: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4));"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

app/views/bikes/my_own.html.erb
<h1>Bikes#my_own</h1>
<p>Find me in app/views/bikes/my_own.html.erb</p>

app/views/bikes/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6 mt-3">
      <h4>Add your Bike here:</h4>
      <%= render 'form', bike: @bike  %>
    <%= link_to "back", bikes_path %>
    </div>

  </div>
</div>

app/views/bikes/show.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-sm-12 col-md-6">
      <%= cl_image_tag @bike.photo.key, height: 300, width: 350, crop: :fill, :quality=>"auto", :fetch_format=>:auto, class: 'm-1 text-center' %>
    </div>
    <div class="col-sm-12 col-md-6">
      <h3>Category: <%= @bike.category %></h3>
      <strong>Name: <%= @bike.name %></strong>
      <p><%= @bike.sku  %></p>
      <p>Amount: <%= humanized_money_with_symbol(@bike.price) %></p>
      <div class="purchse mb-2">
        <%= form_tag orders_path do %>
          <%= hidden_field_tag 'bike_id', @bike.id %>
          <%= submit_tag 'Rent', class: 'btn btn-primary' %>
        <% end %>
      </div>

    </div>
  </div>
</div>


<!--bike REVIEWS!-->

<div class="container">
  <div class="row">
    <div class="col-md-6 mt-4">
      <h4>Reviews</h4>
      <% unless !user_signed_in? %>
        <% pre_review = @bike.reviews.find { |review| review.user_id == current_user.id} %>
        <% if @bike.reviews.empty? %>
          <p>Be the first to add a review</p>
        <% else %>
          <ul class="list-group">
            <% @bike.reviews.each do |review| %>
              <li class="list-group-item d-flex justify-content-between align-items-center mt-2">
                <span class="badge badge-primary badge-pill">
                  <% counter = 0 %>
                  <% 5.times do %>
                    <i class="fa <%= review.rating > counter ? 'fa-star' : 'fa-star-o' %>"></i>
                    <% counter += 1 %>
                  <% end %>
                </span>
                <p id="review-<%= review.id %>"><%= review.content %></p>
              </li>
              <small>by <%= review.user.nickname  %></small>
            <% end %>
          </ul>
          <% if pre_review %>
            <%= button_to 'Delete Review', bike_review_path(@bike, pre_review), method: :delete, remote: true %>
          <% end %>
        <% end %>
      <% else %>
        <ul class="list-group">
          <% @bike.reviews.each do |review| %>
            <li class="list-group-item d-flex justify-content-between align-items-center mt-2">
              <span class="badge badge-primary badge-pill">
                <% counter = 0 %>
                <% 5.times do %>
                  <i class="fa <%= review.rating > counter ? 'fa-star' : 'fa-star-o' %>"></i>
                  <% counter += 1 %>
                <% end %>
              </span>
              <p id="review-<%= review.id %>"><%= review.content %></p>
            </li>
            <small>by <%= review.user.nickname  %></small>
          <% end %>
        </ul>
      <% end %>

      <small> <%= pluralize @bike.reviews.size, "Review" %></small>

      <%= render "reviews/new", bike: @bike, review: @review %>

      <div class='mt-2 mb-2'>
        <% if current_user.try(:admin?) || current_user == @bike.owner %>
          <% if policy(@bike).edit? %>
            <%= link_to 'Edit', edit_bike_path(@bike), class: "btn btn-outline-primary" %> |
          <% end %>
          <% if policy(@bike).destroy? %>
            <%= link_to 'Delete', bike_path(@bike), method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %> |
          <% end %>
        <% end %>
        <%= link_to 'Back', bikes_path, class: 'btn btn-secondary' %>
      </div>

    </div>
  </div>
</div>
<small>Reload page to get updated map display</small>
<div data-turbolinks="false">
  <div class="mb-3" id="map" style="width: 100%; height: 250px;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bikebnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/orders/show.html.erb
<div class="container">
  <div class="row py-4">
    <div class="col-md-3"><%= image_tag @order.bike.photo, width: '100%' %></div>
    <div class="col">
      <h1>Order #<%= @order.id %> <small><span class="badge badge-primary"><%= @order.state %></span></small></h1>
      <ul class="list-unstyled">
        <li><strong>ISSUED ON</strong> <%= @order.created_at.to_date %></li>
        <li><strong>BIKE</strong> <%= @order.bike.name %> [<%= @order.bike_sku %>]</li>
        <li><strong>TOTAL</strong> <%= humanized_money_with_symbol @order.amount %></li>
        </li>
      </ul>
      <p>Estimated delivery in <strong>2 business days</strong></p>
    </div>
  </div>
  <%= link_to "back", bikes_path %>
</div>

app/views/pages/home.html.erb
<div class="content">
  <h1>Find A Bike of Your Choice</h1>
  <p>
    <span id="banner-typed-text"></span>
  </p>
  <div class="m-5">
    <p><%= link_to "Rent A Bike", bikes_path, class: "btn btn-primary btn-lg btn-block" %></p>
    <p><%= link_to "Put A Bike Up For Rent", new_bike_path, class: "btn btn-success btn-lg btn-block" %></p>
  </div>
</div>

app/views/pages/payment.html.erb
<div class="container">
  <div class="row text-center">
    <div class="col-md-8">
      <h2>Thank you for your payment</h2>
      <%= link_to "OK", bike_path(@bike), class:"btn btn-success btn-payment-ok" %>
    </div>
  </div>
</div>

app/views/payments/new.html.erb
<div class="container">
  <div class="row py-4">
    <div class="col-md-3"><%= image_tag @order.bike.photo, width: '100%' %></div>
    <div class="col">
      <h1>Checkout summary</h1>
      <p>Purchase of <strong><%= @order.bike.name %></strong> for <strong><%= humanized_money_with_symbol @order.amount %></strong></p>
      <button id="pay" class="btn btn-primary">Pay</button>
      <script src="https://js.stripe.com/v3/"></script>
      <script>
        const paymentButton = document.getElementById('pay');
        paymentButton.addEventListener('click', () => {
          const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
          stripe.redirectToCheckout({
            sessionId: '<%= @order.checkout_session_id %>'
          });
        });
      </script> -->
    </div>
  </div>
</div>

app/views/reviews/_new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= simple_form_for [bike, review], remote: true do |f| %>
        <%= f.input :content %>
        <%= f.input :rating, collection: (1..5).to_a, label: "Rate the write up" %>
        <%= f.submit "Save your review", class: "btn btn-outline-info" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <h1>Bikebnb</h1>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active mr-1 mb-1">
          <%= link_to "Add a Bike", new_bike_path, class: "nav-link btn btn-outline-success" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.avatar.attached? %>
            <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
            <% else %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>